name: CI


on:
  push:
    branches:
      - main
  pull_request:
  
jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt

      - name: Check fromatting 
        run: python -m ruff format app --diff

      - name: Run lint
        run: python -m ruff check app

      - name: Run Tests
        run: python -m pytest app/tests -v
      
      - name: Configure AWS credentials
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: docker build -t devops-health-api:${{ github.sha }} .

      - name: Push Docker image to ECR
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker tag devops-health-api:${{ github.sha }} ${{ secrets.ECR_REPOSITORY_URI }}:${{ github.sha }}
          docker tag devops-health-api:${{ github.sha }} ${{ secrets.ECR_REPOSITORY_URI }}:latest
          docker push ${{ secrets.ECR_REPOSITORY_URI }}:${{ github.sha }}
          docker push ${{ secrets.ECR_REPOSITORY_URI }}:latest
